version: "3"
services:
  es01:
    build: docker/elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks: [elastic]
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - 5601:5601
    networks: [elastic]
networks:
  elastic: